# Dagger workspace configuration
# Install modules with: dagger install <module>
# Example:
#   dagger install github.com/dagger/dagger/modules/wolfi

[modules.dagger-dang-sdk]
source = "github.com/dagger/dang-sdk"

[modules.editor]
source = "github.com/vito/editor"

[modules.committer]
source = "committer"

[modules.staff]
source = "staff"

[modules.contributor]
source = "contributor"

[modules.contributor.settings]
githubToken = "cmd://gh auth token"

[modules.context]
source = "context"











[sdks.dang]
module = "dagger-dang-sdk"

[sdks.dang.scopes.claude]
is-module = true
name = "claude"

[sdks.dang.scopes.codex]
is-module = true
clients = ["github.com/dagger/dagger/modules/wolfi@f2aefc20cf41b5ed7922df7244e0f10ddc6031f7"]
name = "codex"

[sdks.dang.scopes.committer]
is-module = true
name = "committer"

[sdks.dang.scopes.context]
is-module = true
name = "context"

[sdks.dang.scopes.contributor]
is-module = true
name = "contributor"

[sdks.dang.scopes.delegate]
is-module = true
name = "delegate"

[sdks.dang.scopes.sandbox]
is-module = true
name = "sandbox"

[sdks.dang.scopes.staff]
is-module = true
name = "staff"
